---
- name: Build and Push Docker Image
  hosts: localhost
  connection: local
  tags: ["build"]
  tasks:
    - name: Get ECR login password using IAM Role
      ansible.builtin.shell: "aws ecr get-login-password --region {{ aws_region }}"
      register: ecr_password
      no_log: true

    - name: Log in to ECR
      community.docker.docker_login:
        registry_url: "{{ registry }}"
        username: AWS
        password: "{{ ecr_password.stdout }}"

    - name: Build and push image
      community.docker.docker_image:
        build:
          path: .
        name: "{{ registry }}/{{ repo_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: build

- name: Deploy Container to EC2
  hosts: ec2_ubuntu
  become: true
  tags: ["deploy"]
  tasks:
    - name: Log in to ECR on remote host
      community.docker.docker_login:
        registry_url: "{{ registry }}"
        username: AWS
        password: "{{ lookup('pipe', 'aws ecr get-login-password --region ' + aws_region) }}"

    - name: Pull and Run New Container
      community.docker.docker_container:
        name: "{{ repo_name }}"
        image: "{{ registry }}/{{ repo_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "8081:5001"
